src/apps/cars/urls.py
from src.apps.cars.views import CarsListView, CarsDetailView, serialized_cars
from django.urls import path

app_name = 'cars'

urlpatterns = [
    path(
        '',
        CarsListView.as_view(),
        name='car_list',
    ),
    path(
        '<slug:car_slug>/',
        CarsDetailView.as_view(),
        name='car_detail',
    ),
    path(
        'api/car/json/',
        serialized_cars,
    )
]

src/apps/dealers/urls.py
from django.urls import path

from src.apps.dealers.views import DealersListView, DealersDetailView, serialized_dealers

app_name = 'dealers'

urlpatterns = [
    path(
        '',
        DealersListView.as_view(),
        name='dealer_list',
    ),
    path(
        '<int:dealer_pk>/',
        DealersDetailView.as_view(),
        name='dealer_detail',
    ),
    path(
        'api/car/json/',
        serialized_dealers,
    )
]

src/django_cardealer/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from src.django_cardealer import settings
from src.django_cardealer.views import MainPageTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageTemplateView.as_view(),),
    path('cars/', include('src.apps.cars.urls', namespace='cars')),
    path('dealers/', include('src.apps.dealers.urls', namespace='dealers')),
    path('orders/', include('src.apps.orders.urls', namespace='orders')),
    path('newsletters/', include('src.apps.newsletters.urls', namespace='newsletters')),
    path('users/', include("src.apps.users.urls", namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/dealers/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
USER_MODEL = get_user_model()


class Dealer(models.Model):
    title = models.CharField(max_length=100)

    email = models.EmailField(
        max_length=50,
        unique=True
    )

    city = models.ForeignKey(
        'dealers.City',
        on_delete=models.CASCADE,
        default=''
    )

    user = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
        related_name='orders',
    )

    class Meta:
        verbose_name = 'Dealer'
        verbose_name_plural = 'Dealers'

    def __str__(self):
        return self.title


class City(models.Model):
    name = models.CharField(max_length=40)

    country = models.ForeignKey(
        'dealers.Country',
        on_delete=models.CASCADE,
        related_name='cities',
        default=''
    )

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=40)

    code = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name

src/apps/dealers/views.py
from django.core import serializers
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
# Create your views here.
from src.apps.dealers.models import Dealer

from src.apps.cars.models import Car


class DealersListView(ListView):
    model = Dealer.objects.all()
    context_object_name = 'dealers'
    template_name = 'dealers/list.html'

    def get_queryset(self):
        return Dealer.objects.all()  # FIX ME!!!


class DealersDetailView(DetailView):
    model = Dealer
    context_object_name = 'dealers'
    pk_url_kwarg = 'dealer_pk'
    template_name = 'dealers/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.filter(dealer=self.object)
        return context


def serialized_dealers(request):
    data = serializers.serialize('json', Dealer.objects.all())
    return HttpResponse(request.method + '<br>' + data)

src/apps/dealers/templates/dealers/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealer details</title>
</head>
<body>
{% include "navbar.html" %}
<h1 align="center">Dealer: {{ object.title }}</h1>
<div align="center">
    <p>Email: {{ object.email }}</p>
    <p>City: {{ object.city.name }}, {{ object.city.country.name }}</p>
    <p>Cars:</p>
        <table class="table">
        <thead class="thead-light col-form-label-lg">
        <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>Price</th>
            <th>City</th>
            <th>Status</th>
            <th>Registration Date</th>
            <th>Details</th>
        </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{ car.model.brand.name }}</td>
                <td>{{ car.model.name }}</td>
                <td>{{ car.price }}</td>
                <td>{{ car.dealer.city }}</td>
                <td>{{ car.status }}</td>
                <td>{{ car.first_registration_date }}</td>
                <td><a href="{% url 'cars:car_detail' car.slug %}">See details...</a></td>
            </tr>
        </tbody>

        {% empty %}
        <li>Sorry, there's no car yet. Come here later :)</li>
        {% endfor %}
        </table>
</div>
{% include "footer.html" %}
</body>
</html>

src/apps/dealers/templates/dealers/list.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Dealers list</title>
</head>
<body>
{% include "navbar.html" %}
<h1 align="center">Dealers</h1>
<table class="table">
    <thead align="center" class="thead-light col-form-label-lg">
        <tr>
            <th>Dealer's name</th>
            <th>City</th>
            <th>Email</th>


        </tr>
    </thead>
    <tbody align="center">
        {% for dealer in dealers %}
        <tr>
            <td><a href="{% url 'dealers:dealer_detail' dealer.id %}">{{ dealer.title }}</a></td>
            <td>{{ dealer.city }}, {{ dealer.city.country }}</td>
            <td>{{ dealer.email }}</td>
        {% empty %}
        <li align="center">Sorry, there's no dealers yet. Come here later :)</li>
        {% endfor %}
        </tr>
    </tbody>
</table>
{% include "footer.html" %}
</body>
</html>