src/apps/cars/urls.py
from src.apps.cars.views import CarsListView, CarsDetailView, serialized_cars
from django.urls import path

app_name = 'cars'

urlpatterns = [
    path(
        '',
        CarsListView.as_view(),
        name='car_list',
    ),
    path(
        '<slug:car_slug>/',
        CarsDetailView.as_view(),
        name='car_detail',
    ),
    path(
        'api/car/json/',
        serialized_cars,
    )
]

src/apps/dealers/urls.py
from django.urls import path

from src.apps.dealers.views import DealersListView, DealersDetailView, serialized_dealers

app_name = 'dealers'

urlpatterns = [
    path(
        '',
        DealersListView.as_view(),
        name='dealer_list',
    ),
    path(
        '<int:dealer_pk>/',
        DealersDetailView.as_view(),
        name='dealer_detail',
    ),
    path(
        'api/car/json/',
        serialized_dealers,
    )
]

src/apps/newsletters/urls.py
from django.urls import path

from src.apps.newsletters.views import NewNewsLetterView, SuccessTemplateView

app_name = 'newsletters'

urlpatterns = [
    path(
        'new/',
        NewNewsLetterView.as_view(),
        name='new_newsletter',
    ),
    path(
        'success/',
        SuccessTemplateView.as_view(),
        name='success',
    ),
]

src/apps/orders/urls.py
from django.urls import path

from src.apps.orders.views import OrdersListView, OrdersDetailView, serialized_orders

app_name = 'orders'

urlpatterns = [
    path(
        '',
        OrdersListView.as_view(),
        name='order_list',
    ),
    path(
        '<int:order_pk>/',
        OrdersDetailView.as_view(),
        name='order_detail',
    ),
    path(
        'api/order/json/',
        serialized_orders,
    )
]

src/apps/users/urls.py
from django.urls import path
from .views import RegisterUser, LoginUser, logout_user

app_name = "main"


urlpatterns = [
    path('register/', RegisterUser.as_view(), name="register"),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

src/django_cardealer/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from src.django_cardealer import settings
from src.django_cardealer.views import MainPageTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageTemplateView.as_view(),),
    path('cars/', include('src.apps.cars.urls', namespace='cars')),
    path('dealers/', include('src.apps.dealers.urls', namespace='dealers')),
    path('orders/', include('src.apps.orders.urls', namespace='orders')),
    path('newsletters/', include('src.apps.newsletters.urls', namespace='newsletters')),
    path('users/', include("src.apps.users.urls", namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/cars/models.py
import django.utils.timezone
from django.contrib.auth import get_user_model
from django.db import models

AUTH_USER_MODEL = get_user_model()


# Create your models here.


class Car(models.Model):
    color = models.ForeignKey(
        'cars.Color',
        on_delete=models.CASCADE,
    )

    dealer = models.ForeignKey(
        'dealers.Dealer',
        on_delete=models.CASCADE,
        null=True
    )

    model = models.ForeignKey(
        'cars.Model',
        on_delete=models.CASCADE,
    )

    ENGINE_TYPE_STRAIGHT = 'straight'
    ENGINE_TYPE_INLINE = 'inline'
    ENGINE_TYPE_FLAT = 'flat'
    ENGINE_TYPE_V = 'v'

    ENGINE_TYPES = (
        (ENGINE_TYPE_STRAIGHT, 'Straight'),
        (ENGINE_TYPE_INLINE, 'Inline'),
        (ENGINE_TYPE_FLAT, 'Flat'),
        (ENGINE_TYPE_V, 'V')
    )

    engine_type = models.CharField(
        max_length=75,
        choices=ENGINE_TYPES,
        default=ENGINE_TYPE_STRAIGHT,
    )

    POLLUTANT_CLASS_Aa = "class A+"
    POLLUTANT_CLASS_A = "class A"
    POLLUTANT_CLASS_B = "class B"
    POLLUTANT_CLASS_C = "class C"
    POLLUTANT_CLASS_D = "class D"
    POLLUTANT_CLASS_E = "class E"
    POLLUTANT_CLASS_F = "class F"
    POLLUTANT_CLASS_G = "class G"

    POLLUTANT_CLASS_CHOICES = (
        (POLLUTANT_CLASS_Aa, "A+"),
        (POLLUTANT_CLASS_A, "A"),
        (POLLUTANT_CLASS_B, "B"),
        (POLLUTANT_CLASS_C, "C"),
        (POLLUTANT_CLASS_D, "D"),
        (POLLUTANT_CLASS_E, "E"),
        (POLLUTANT_CLASS_F, "F"),
        (POLLUTANT_CLASS_G, "G"),
    )
    pollutant_class = models.CharField(
        max_length=30,
        choices=POLLUTANT_CLASS_CHOICES,
        default=POLLUTANT_CLASS_Aa,
        blank=True
    )

    price = models.PositiveIntegerField(default=0)

    property = models.ManyToManyField('cars.Property')

    fuel_type = models.ForeignKey(
        'cars.FuelType',
        on_delete=models.CASCADE,
        related_name='cars'
    )

    STATUS_PENDING = 'pending'
    STATUS_PUBLISHED = 'published'
    STATUS_SOLD = 'sold'
    STATUS_ARCHIVED = 'archived'

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending Car Sell"),
        (STATUS_PUBLISHED, "Published"),
        (STATUS_SOLD, "Sold"),
        (STATUS_ARCHIVED, "Archived"),
    )

    slug = models.SlugField(max_length=75)

    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=STATUS_PENDING,
        blank=True
    )
    doors = models.SmallIntegerField(default=4)

    capacity = models.PositiveIntegerField(default=0)

    MECHANICAL = 'mechanical'
    AUTOMATIC = 'automatic'
    VARIATOR = 'variator'
    ROBOTIC = 'robotic'

    GEAR_CASES = (
        (MECHANICAL, 'Mechanical'),
        (AUTOMATIC, 'Automatic'),
        (VARIATOR, 'Variator'),
        (ROBOTIC, 'Robotic')
    )

    gear_case = models.CharField(
        max_length=75,
        choices=GEAR_CASES,
        default=AUTOMATIC)

    number = models.CharField(max_length=30)

    sitting_place = models.PositiveSmallIntegerField(default=4)

    first_registration_date = models.DateTimeField(default=django.utils.timezone.now)

    engine_power = models.PositiveIntegerField(default=0)

    picture = models.ForeignKey('cars.Picture', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "Car"
        verbose_name_plural = "Cars"

    def __str__(self):
        return self.slug


class Color(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Color'
        verbose_name_plural = 'Colors'


class Brand(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'


class Model(models.Model):
    brand = models.ForeignKey('cars.Brand', on_delete=models.CASCADE)
    name = models.CharField(max_length=75)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Model'
        verbose_name_plural = 'Models'


class Property(models.Model):
    CATEGORY_0 = 'Quadricycle'
    CATEGORY_A = 'Mini'
    CATEGORY_B = 'Small'
    CATEGORY_C = 'Medium'
    CATEGORY_D = 'Large'
    CATEGORY_E = 'Executive'
    CATEGORY_F = 'Luxury'
    CATEGORY_S = 'Sports coupes'
    CATEGORY_M = 'Multi purpose'
    CATEGORY_J = 'Sport utility'

    CATEGORY_CHOICES = (
        (CATEGORY_0, 'Quadricycle'),
        (CATEGORY_A, 'Mini'),
        (CATEGORY_B, 'Small'),
        (CATEGORY_C, 'Medium'),
        (CATEGORY_D, 'Large'),
        (CATEGORY_E, 'Executive'),
        (CATEGORY_F, 'Luxury'),
        (CATEGORY_M, 'Multi purpose'),
        (CATEGORY_J, 'Sport utility'),
    )

    name = models.CharField(max_length=75)

    category = models.CharField(
        max_length=75,
        choices=CATEGORY_CHOICES,
        default=CATEGORY_0,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'


class FuelType(models.Model):
    FUEL_TYPE_PETROL = 'petrol'
    FUEL_TYPE_DIESEL = 'diesel'
    FUEL_TYPE_ELECTRIC = 'electric'

    FUEL_TYPE_CHOICES = (
        (FUEL_TYPE_PETROL, 'Petrol'),
        (FUEL_TYPE_DIESEL, 'Diesel'),
        (FUEL_TYPE_ELECTRIC, 'Electric')
    )

    fueltype = models.CharField(
        max_length=30,
        choices=FUEL_TYPE_CHOICES,
        default=FUEL_TYPE_PETROL,
    )

    def __str__(self):
        return self.fueltype

    class Meta:
        verbose_name = 'Fuel Type'
        verbose_name_plural = 'Fuel Types'


class Picture(models.Model):
    url = models.ImageField(
        upload_to='static/pictures',
        max_length=255,
        null=True,
        blank=True,
    )
    position = models.IntegerField()
    metadata = models.TextField()

    def __str__(self):
        return self.url.name

    class Meta:
        verbose_name = 'Picture'
        verbose_name_plural = 'Pictures'

src/apps/dealers/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
USER_MODEL = get_user_model()


class Dealer(models.Model):
    title = models.CharField(max_length=100)

    email = models.EmailField(
        max_length=50,
        unique=True
    )

    city = models.ForeignKey(
        'dealers.City',
        on_delete=models.CASCADE,
        default=''
    )

    user = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
        related_name='orders',
    )

    class Meta:
        verbose_name = 'Dealer'
        verbose_name_plural = 'Dealers'

    def __str__(self):
        return self.title


class City(models.Model):
    name = models.CharField(max_length=40)

    country = models.ForeignKey(
        'dealers.Country',
        on_delete=models.CASCADE,
        related_name='cities',
        default=''
    )

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=40)

    code = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name

src/apps/newsletters/models.py
from django.db import models


# Create your models here.
class NewsLetter(models.Model):
    email = models.EmailField(max_length=75, unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'News Letter'
        verbose_name_plural = 'News Letters'

src/apps/orders/models.py
# import phone_field
from django.db import models


# Create your models here.
class Order(models.Model):
    car = models.ForeignKey(
        'cars.Car',
        on_delete=models.CASCADE
    )
    status = models.CharField(max_length=30)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20, null=True)
    message = models.TextField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

src/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    DEALER = 'Dealer'
    CUSTOMER = 'Customer'

    ROLE_CHOICES = (
        (DEALER, 'Dealer'),
        (CUSTOMER, 'Customer'),
    )
    role = models.CharField(max_length=255, choices=ROLE_CHOICES)

src/apps/newsletters/forms.py
from django import forms

from src.apps.newsletters.models import NewsLetter


class NewsLetterModelForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = ['email']
        labels = {'Email': ''}

src/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from src.apps.users.models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    role = forms.ChoiceField(label='Choose your role', choices=User.ROLE_CHOICES)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'role')

src/apps/cars/views.py
from django.core import serializers
from django.http import HttpResponse
from src.apps.cars.models import Car
from django.views.generic import ListView, DetailView


class CarsListView(ListView):
    model = Car.objects.all()
    context_object_name = 'cars'
    template_name = 'cars/list.html'

    def get_queryset(self):
        return Car.objects.all()


class CarsDetailView(DetailView):
    model = Car
    context_object_name = 'cars'
    slug_url_kwarg = 'car_slug'
    template_name = 'cars/detail.html'


def serialized_cars(request):
    data = serializers.serialize('json', Car.objects.all())
    return HttpResponse(request.method + '<br>' + data)

src/apps/dealers/views.py
from django.core import serializers
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
# Create your views here.
from src.apps.dealers.models import Dealer

from src.apps.cars.models import Car


class DealersListView(ListView):
    model = Dealer.objects.all()
    context_object_name = 'dealers'
    template_name = 'dealers/list.html'

    def get_queryset(self):
        return Dealer.objects.all()  # FIX ME!!!


class DealersDetailView(DetailView):
    model = Dealer
    context_object_name = 'dealers'
    pk_url_kwarg = 'dealer_pk'
    template_name = 'dealers/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cars'] = Car.objects.filter(dealer=self.object)
        return context


def serialized_dealers(request):
    data = serializers.serialize('json', Dealer.objects.all())
    return HttpResponse(request.method + '<br>' + data)

src/apps/newsletters/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from src.apps.newsletters.forms import NewsLetterModelForm


# Create your views here.


class NewNewsLetterView(FormView):
    template_name = 'newsletters/subscribe.html'
    form_class = NewsLetterModelForm
    success_url = reverse_lazy('newsletters:success')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class SuccessTemplateView(TemplateView):
    template_name = 'newsletters/success.html'

src/apps/orders/views.py
from django.core import serializers
from django.http import HttpResponse
from django.views.generic import ListView, DetailView

# Create your views here.
from src.apps.orders.models import Order


class OrdersListView(ListView):
    model = Order.objects.all()
    context_object_name = 'orders'
    template_name = 'orders/list.html'

    def get_queryset(self):
        return Order.objects.all()


class OrdersDetailView(DetailView):
    model = Order
    context_object_name = 'orders'
    pk_url_kwarg = 'order_pk'
    template_name = 'orders/detail.html'


def serialized_orders(request):
    data = serializers.serialize('json', Order.objects.all())
    return HttpResponse(request.method + '<br>' + data)

src/apps/users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegisterUserForm
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

from .utils import DataMixin


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')


# @login_required
# def index(request):
#     return render(request, 'users/index.html')


class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def logout_user(request):
    template_name = 'users/logged_out.html'
    logout(request)
    return render(request, template_name)

src/django_cardealer/views.py
from django.views.generic import TemplateView


class MainPageTemplateView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

src/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small text-white pt-4 bg-dark">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Car Dealer</h5>
          <p>This is my pet project based on Django framework. I started it while studying at CURSOR.EDUCATION.</p>
          <p>Thank you for your attention, hope you enjoy it! :)</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#">Link 1</a>
          </li>
          <li>
            <a href="#">Link 2</a>
          </li>
          <li>
            <a href="#">Link 3</a>
          </li>
          <li>
            <a href="#">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#">Link 1</a>
          </li>
          <li>
            <a href="#">Link 2</a>
          </li>
          <li>
            <a href="#">Link 3</a>
          </li>
          <li>
            <a href="#">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Car Dealer</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
{% include "navbar.html" %}
{% load static %}
<h1>Hello there! Here you can see an information about our activity</h1>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        {% for car in cars %}
      <img src="{{ apps.car.picture.url }}" alt="picture">
        {% endfor %}
    </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h3>Also, you can subscribe to our newsletters! </h3>
<p><h2><a href="{% url 'newsletters:new_newsletter' %}">Subscribe!</a></h2>
<h3>Thank you for visiting our website!</h3>
{% include "footer.html" %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

src/templates/navbar.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<nav class="navbar navbar-expand-xl navbar-light bg-dark">
  <a class="navbar-brand" href="/" style="color: gold"><h1>Car Dealer</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cars:car_list' %}" style="color: white"><h3>Cars</h3><span class="sr-only">(current)</span></a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dealers:dealer_list' %}" style="color: white"><h3>Dealers</h3></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'orders:order_list' %}" style="color: white"><h3>Orders</h3></a>
      </li>
      {% endif %}
    </ul>
  <span class="user">
    <ul class="nav justify-content-end">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" style="color: gold"><h3> {{ user }}</h3></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}" style="color: red"><h3>Logout </h3></a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" style="color: orange"><h3>You're not logged in</h3></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="/users/login/" style="color: dodgerblue"><h3>Login</h3></a>
      </li>
      {% endif %}
    </ul>
  </span>
  </div>
</nav>