src/apps/orders/urls.py
from django.urls import path

from src.apps.orders.views import OrdersListView, OrdersDetailView, serialized_orders

app_name = 'orders'

urlpatterns = [
    path(
        '',
        OrdersListView.as_view(),
        name='order_list',
    ),
    path(
        '<int:order_pk>/',
        OrdersDetailView.as_view(),
        name='order_detail',
    ),
    path(
        'api/order/json/',
        serialized_orders,
    )
]

src/django_cardealer/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from src.django_cardealer import settings
from src.django_cardealer.views import MainPageTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageTemplateView.as_view(),),
    path('cars/', include('src.apps.cars.urls', namespace='cars')),
    path('dealers/', include('src.apps.dealers.urls', namespace='dealers')),
    path('orders/', include('src.apps.orders.urls', namespace='orders')),
    path('newsletters/', include('src.apps.newsletters.urls', namespace='newsletters')),
    path('users/', include("src.apps.users.urls", namespace='users')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/orders/models.py
# import phone_field
from django.db import models


# Create your models here.
class Order(models.Model):
    car = models.ForeignKey(
        'cars.Car',
        on_delete=models.CASCADE
    )
    status = models.CharField(max_length=30)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20, null=True)
    message = models.TextField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

src/apps/orders/views.py
from django.core import serializers
from django.http import HttpResponse
from django.views.generic import ListView, DetailView

# Create your views here.
from src.apps.orders.models import Order


class OrdersListView(ListView):
    model = Order.objects.all()
    context_object_name = 'orders'
    template_name = 'orders/list.html'

    def get_queryset(self):
        return Order.objects.all()


class OrdersDetailView(DetailView):
    model = Order
    context_object_name = 'orders'
    pk_url_kwarg = 'order_pk'
    template_name = 'orders/detail.html'


def serialized_orders(request):
    data = serializers.serialize('json', Order.objects.all())
    return HttpResponse(request.method + '<br>' + data)

src/apps/orders/templates/orders/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order details</title>
</head>
<body>
{% include "navbar.html" %}
<div class="card" align="center" >
<div class="card-body" align="center">
<h2 class="card-title" align="center">Order: {{ object.id }}</h2>
<h6 class="card-subtitle mb-2 text-muted">Status: {{ object.status }}</h6>
    <h1 class="card-text" style="color: darkslateblue" align="center">{{ object.first_name }} {{ object.last_name }}</h1>

    <h4 class="card-text">Car: {{ object.car.model.brand.name }} {{ object.car.model.name }}</h4>
<div class="card-footer text-center">
    <p>Message:</p>
    <p>{{ object.message }}</p>
</div>
<hr>
<div>
  <a class="text-lg-left">Email: {{ object.email }}</a>
    <hr>
  <a class="text-lg-right">Phone: {{ object.phone }}</a>
</div>
</div>
</div>
{% include "footer.html" %}
</body>
</html>

src/apps/orders/templates/orders/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order list</title>
</head>
<body>
{% include "navbar.html" %}
<h1 align="center">Orders</h1>
<table class="table">
    <thead align="center" class="thead-light col-form-label-lg">
        <tr>
            <th>ID</th>
            <th>Customer</th>
            <th>Car</th>
            <th>Price</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody align="center">
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td><a href="{% url 'orders:order_detail' order.id %}">{{ order.first_name }} {{ order.last_name }}</a></td>
                <td>{{ order.car.model.brand }} {{ order.car.model }}</td>
                <td> {{ order.car.price }}</td>
                <td>{{ order.car.status }}</td>
            </tr>
        {% empty %}
        <h3>Sorry, there's no order yet. Come here later :)</h3>
        {% endfor %}
    </tbody>
</table>
{% include "footer.html" %}
</body>
</html>